trigger:
- master   # change to main if your branch is main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  publishDir: '$(Build.ArtifactStagingDirectory)/publish'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'

# Restore
- script: dotnet restore
  displayName: 'Restore NuGet Packages'

# Build
- script: dotnet build -c $(buildConfiguration) --no-restore
  displayName: 'Build'

# Test
- script: dotnet test --no-build
  displayName: 'Run Tests'

- script: |
    dotnet publish InventoryAPI.csproj `
      -c $(buildConfiguration) `
      -o $(publishDir)
  displayName: 'Publish Web API'


- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(publishDir)'
    artifactName: 'drop'


- task: AzureWebApp@1
  displayName: 'Deploy to Azure'
  inputs:
    azureSubscription: 'AzureServiceConnection'
    appName: 'InventoryAPISeema'
    package: '$(publishDir)'

