trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'

- script: dotnet restore
  displayName: 'Restore NuGet Packages'

- script: dotnet build --configuration Release
  displayName: 'Build Project'

- script: dotnet test
  displayName: 'Run Unit Tests'
